import type { MatchSetup, RosterPlayer } from "@bpc/shared-types";
import { teamLogoPath } from "@bpc/shared-types";

export type TeamInfo = {
  teamKey: string;
  teamName: string;
  players: RosterPlayer[];
};

export function listTeamsFromRoster(roster: RosterPlayer[]): TeamInfo[] {
  const byKey = new Map<string, TeamInfo>();

  for (const p of roster) {
    const teamKey =
      p.teamKey ??
      slugify(p.teamName ?? "unknown");
    const teamName = p.teamName ?? titleFromKey(teamKey);

    const existing = byKey.get(teamKey);
    if (existing) {
      existing.players.push(p);
      if (p.teamName && !existing.teamName) {
        existing.teamName = p.teamName;
      }
    } else {
      byKey.set(teamKey, {
        teamKey,
        teamName,
        players: [p],
      });
    }
  }

  return [...byKey.values()].sort((a, b) =>
    a.teamName.localeCompare(b.teamName),
  );
}

/**
 * Collapse a team key down to just its alphanumerics so keys generated by
 * different code paths (CSV import keeps whatever was typed, bpcleague sync
 * uses underscores, some UI pickers use hyphens) still match each other.
 * "team-liquid", "team_liquid", "Team Liquid" all normalize to "teamliquid".
 */
function normalizeKey(k: string): string {
  return k.trim().toLowerCase().replace(/[^a-z0-9]+/g, "");
}

export function getTeamByKey(
  roster: RosterPlayer[],
  teamKey: string,
): TeamInfo | undefined {
  const target = normalizeKey(teamKey);
  return listTeamsFromRoster(roster).find(
    (t) => normalizeKey(t.teamKey) === target,
  );
}

export function playersForMatchSide(
  roster: RosterPlayer[],
  matchSetup: MatchSetup | null | undefined,
  side: "radiant" | "dire",
): RosterPlayer[] {
  if (!matchSetup) return [];
  const key =
    side === "radiant"
      ? matchSetup.radiantTeamKey
      : matchSetup.direTeamKey;
  return getTeamByKey(roster, key)?.players ?? [];
}

export function findPlayerOnSide(
  roster: RosterPlayer[],
  matchSetup: MatchSetup | null | undefined,
  side: "radiant" | "dire",
  opts: { steam32?: number; displayName?: string },
): RosterPlayer | undefined {
  const pool = playersForMatchSide(roster, matchSetup, side);
  if (opts.steam32 !== undefined) {
    return pool.find((p) => p.steam32 === opts.steam32);
  }
  if (opts.displayName) {
    const norm = opts.displayName.trim().toLowerCase();
    return pool.find((p) => p.displayName.trim().toLowerCase() === norm);
  }
  return undefined;
}

export function findPlayerInMatch(
  roster: RosterPlayer[],
  matchSetup: MatchSetup | null | undefined,
  opts: { steam32?: number; displayName?: string },
): RosterPlayer | undefined {
  return (
    findPlayerOnSide(roster, matchSetup, "radiant", opts) ??
    findPlayerOnSide(roster, matchSetup, "dire", opts)
  );
}

export function teamLogoUrl(teamKey: string): string {
  return teamLogoPath(teamKey);
}

function slugify(s: string): string {
  return s.trim().toLowerCase().replace(/\s+/g, "_");
}

function titleFromKey(key: string): string {
  return key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
